title: "Unix und ich"
paginate: 10
theme: midnight
buildDrafts: false
buildFuture: false
buildExpired: false

params:
#title: "Aus dem Tagebuch eines Unix-Fanboys"
#description: "Erlebnisse, Erfahrungen und Erkenntnisse mit einem Betriebssystem"
author: B.S.Ernst
DateFormat: "1.11.2022"

ShowReadingTime: true
ShowWordCount: true
comments: false
hideSummary: false

menu:
  main:
  - identifier: Anfänge
    name: Anfänge
    url: anfang/
    weight: 10
  - identifier: about
    name: About
    url: README/
    weight: 20
  - identifier: impressum
    name: Impressum
    url: impressum/
    weight: 30
      
