title: "Unix und ich"
subtitle: "Erlebnisse mit einem Betriebssystem"
description: "Erlebnisse, Erfahrungen und Abenteuer mit einem Betriebssystem"
paginate: 10
theme: jekyll-theme-midnight
buildDrafts: false
buildFuture: false
buildExpired: false

include:
- _pages
- _posts

params:
#title: "Aus dem Tagebuch eines Unix-Fanboys"
#
author: B.S.Ernst
DateFormat: "1.11.2022"
###

source: [berni51.github.io]

<nav>
  {% for item in site.data.navigation %}
    <a href="{{ item.link }}" {% if item.link == page.url %}class="active"{% endif %}>
      {{ item.name }}
    </a>
  {% endfor %}
</nav>


