title: "Unix und ich"
paginate: 10
theme: minima
buildDrafts: false
buildFuture: false
buildExpired: false

params:
title: "Aus dem Tagebuch eines Unix-Fanboys"
description: "Erlebnisse, Erfahrungen und Erkenntnisse mit einem Betriebssystem"
author: B.S.Ernst
DateFormat: "1.11.2022"

ShowReadingTime: true
ShowWordCount: true
comments: false
hideSummary: false

menu:
  main:
  - identifier: Anfänge
    name: "Die Anfänge"
    url: /anfang.md
    weight: 10
   - identifier: about
     name: About
     url: /README.md
     weight: 20
    - identifier: impressum
      name: Impressum
      url: /impressum.md
      weight: 30
      
