title: "Unix und ich"
subtitle: "Erlebnisse mit einem Betriebssystem"
description: "Erlebnisse, Erfahrungen und Abenteuer mit einem Betriebssystem"
paginate: 10
#theme: jekyll-theme-midnight
buildDrafts: false
buildFuture: false
buildExpired: false

include:
- _pages
- _posts

params:
#title: "Aus dem Tagebuch eines Unix-Fanboys"
#
author: B.S.Ernst
DateFormat: "1.11.2022"
###
lsi: false
safe: true
source: [berni51.github.io]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

###
ShowReadingTime: true
ShowWordCount: true
comments: false
hideSummary: false

[[menu.main]]:
    name: "Blog"
    url: ""
    weight: 1

[[menu.main]]:
    name: "Anfänge"
    url: "_pages/anfang/"
    weight: 2
#
#[[menu.main]]:
#    name: "About"
#    url: "_pages/about.md/"
#    weight: 3

#menu:
#  main:
#  - identifier: Anfänge
#    name: Anfänge
#    url: /anfang/
#    weight: 10
#  - identifier: about
#    name: About
#    url: /README/
#    weight: 20
#  - identifier: impressum
#    name: Impressum
#    url: /impressum/
#    weight: 30
